
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Image, 
                                PageBreak, Table, TableStyle, Frame, PageTemplate)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from PIL import Image as PILImage
import os
from datetime import datetime
from config import OUTPUT_FOLDER


def create_professional_radiology_pdf(report_text, patient_info, kl_grade, confidence, 
                                     gradcam_path=None, output_path=None, 
                                     language='en', prediction_id=None):
    """
    Create a professional radiology report PDF following medical report standards
    
    Format structure:
    - Header: KNEE RADIOLOGICAL REPORT
    - Metadata table: Report Date, Report ID, Patient ID, Age/Sex, Diagnosis
    - Clinical History section
    - Technique section
    - Findings section (with Grad-CAM image)
    - Conclusion section (numbered points)
    - Footer: Generated by AI-Powered System
    """
    
    os.makedirs(OUTPUT_FOLDER, exist_ok=True)
    
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = os.path.join(OUTPUT_FOLDER, f"radiology_report_{timestamp}.pdf")
    
    # Create PDF document
    doc = SimpleDocTemplate(
        output_path, 
        pagesize=letter,
        leftMargin=0.75*inch, 
        rightMargin=0.75*inch,
        topMargin=1*inch, 
        bottomMargin=0.75*inch
    )
    
    story = []
    
    # Define professional styles
    styles = getSampleStyleSheet()
    
    # Title style (main header)
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Title'],
        fontSize=18,
        textColor=colors.HexColor('#1a5490'),  # Professional blue
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
        leading=22
    )
    
    # Section heading style
    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=colors.HexColor('#1a5490'),
        spaceAfter=8,
        spaceBefore=14,
        fontName='Helvetica-Bold',
        leading=14,
        underline=True
    )
    
    # Normal text style
    normal_style = ParagraphStyle(
        'ReportNormal',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
        leading=14,
        fontName='Helvetica'
    )
    
    # Bold text style
    bold_style = ParagraphStyle(
        'ReportBold',
        parent=normal_style,
        fontName='Helvetica-Bold'
    )
    
    # ========================
    # HEADER: Report Title
    # ========================
    story.append(Paragraph("KNEE RADIOLOGICAL REPORT", title_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Add horizontal line
    from reportlab.platypus import HRFlowable
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#1a5490')))
    story.append(Spacer(1, 0.15*inch))
    
    # ========================
    # METADATA TABLE
    # ========================
    report_date = datetime.now().strftime('%B %d, %Y')
    report_id = f"KOA-{datetime.now().strftime('%Y%m%d')}-{prediction_id if prediction_id else '0000'}"
    
    # KL Grade diagnosis names
    kl_diagnoses = {
        0: "No Osteoarthritis",
        1: "Doubtful Osteoarthritis",
        2: "Mild Osteoarthritis",
        3: "Moderate Osteoarthritis",
        4: "Severe Osteoarthritis"
    }
    
    diagnosis_text = f"Kellgren-Lawrence Grade {kl_grade}: {kl_diagnoses.get(kl_grade, 'Osteoarthritis')}"
    
    metadata_data = [
        ['Report Date:', report_date, 'Report ID:', report_id],
        ['Patient ID:', patient_info.get('Name', 'N/A'), 'Age/Sex:', 
         f"{patient_info.get('Age', 'N/A')}/{patient_info.get('Sex', 'N/A')}"],
        ['DIAGNOSIS:', diagnosis_text, '', '']
    ]
    
    metadata_table = Table(metadata_data, colWidths=[1.5*inch, 2.25*inch, 1.25*inch, 2*inch])
    metadata_table.setStyle(TableStyle([
        # Header cells (left column)
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e6f2ff')),
        ('BACKGROUND', (2, 0), (2, -1), colors.HexColor('#e6f2ff')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        
        # Diagnosis row - span and highlight
        ('SPAN', (0, 2), (1, 2)),
        ('SPAN', (2, 2), (3, 2)),
        ('BACKGROUND', (0, 2), (1, 2), colors.HexColor('#d4e6f7')),
        ('FONTNAME', (0, 2), (1, 2), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 2), (1, 2), colors.HexColor('#1a5490')),
        
        # All cells
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    
    story.append(metadata_table)
    story.append(Spacer(1, 0.2*inch))
    
    # ========================
    # PARSE REPORT SECTIONS
    # ========================
    sections = {}
    current_section = None
    current_content = []
    
    lines = report_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
        
        # Check if this is a section header (ends with colon, short length)
        if line.endswith(':') and len(line) < 60 and not line.startswith('-'):
            # Save previous section
            if current_section and current_content:
                sections[current_section] = '\n'.join(current_content)
            # Start new section - normalize to title case
            current_section = line[:-1].strip()  # Remove colon
            # Normalize section names to match expected format
            section_upper = current_section.upper()
            if 'CLINICAL' in section_upper and 'HISTORY' in section_upper:
                current_section = 'Clinical History'
            elif 'TECHNIQUE' in section_upper:
                current_section = 'Technique'
            elif 'FINDING' in section_upper:
                current_section = 'Findings'
            elif 'IMPRESSION' in section_upper or 'CONCLUSION' in section_upper:
                current_section = 'Conclusion'
            elif 'RECOMMENDATION' in section_upper:
                current_section = 'Recommendations'
            elif 'RISK' in section_upper and 'PROFILE' in section_upper:
                current_section = 'Risk Profile'
            elif 'PRECAUTION' in section_upper:
                current_section = 'Precautions'
            elif 'TREATMENT' in section_upper and 'OPTION' in section_upper:
                current_section = 'Treatment Options'
            elif 'FOLLOW' in section_upper and ('UP' in section_upper or 'MONITOR' in section_upper):
                current_section = 'Follow-Up'
            elif 'DISCLAIMER' in section_upper:
                current_section = 'Disclaimer'
            current_content = []
        else:
            if current_section:
                current_content.append(line)
    
    # Save last section
    if current_section and current_content:
        sections[current_section] = '\n'.join(current_content)
    
    # ========================
    # CLINICAL HISTORY SECTION
    # ========================
    if 'Clinical History' in sections:
        story.append(Paragraph("Clinical History:", section_heading_style))
        story.append(Paragraph(sections['Clinical History'], normal_style))
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # TECHNIQUE SECTION
    # ========================
    if 'Technique' in sections:
        story.append(Paragraph("Technique:", section_heading_style))
        technique_text = sections['Technique']
        story.append(Paragraph(technique_text, normal_style))
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # FINDINGS SECTION (with Grad-CAM image)
    # ========================
    if 'Findings' in sections:
        story.append(Paragraph("Findings:", section_heading_style))
        
        findings_text = sections['Findings']
        
        # Prepare Grad-CAM image if available
        gradcam_img = None
        if gradcam_path and os.path.exists(gradcam_path):
            try:
                # Load and resize image
                img = PILImage.open(gradcam_path)
                
                # Target size for image in report
                max_img_width = 2.5 * inch
                max_img_height = 2.5 * inch
                
                # Calculate aspect ratio
                aspect = img.width / img.height
                if aspect > 1:
                    img_width = max_img_width
                    img_height = max_img_width / aspect
                else:
                    img_height = max_img_height
                    img_width = max_img_height * aspect
                
                # Create reportlab Image object
                gradcam_img = Image(gradcam_path, width=img_width, height=img_height)
                
            except Exception as e:
                print(f"Error loading Grad-CAM image: {e}")
                gradcam_img = None
        
        # Create two-column layout: findings text + image
        if gradcam_img:
            findings_para = Paragraph(findings_text, normal_style)
            
            # Create table for side-by-side layout
            findings_data = [[findings_para, gradcam_img]]
            findings_table = Table(
                findings_data,
                colWidths=[4*inch, 2.5*inch],
                rowHeights=None
            )
            findings_table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ALIGN', (1, 0), (1, 0), 'CENTER'),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 5),
                ('TOPPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ]))
            
            story.append(findings_table)
        else:
            # No image, just text
            story.append(Paragraph(findings_text, normal_style))
        
        story.append(Spacer(1, 0.15*inch))
    
    # ========================
    # IMPRESSION/CONCLUSION SECTION
    # ========================
    if 'Conclusion' in sections:
        story.append(Paragraph("Impression:", section_heading_style))
        
        conclusion_text = sections['Conclusion']
        
        # Format conclusion (often has numbered points)
        conclusion_lines = conclusion_text.split('\n')
        for line in conclusion_lines:
            line = line.strip()
            if line:
                story.append(Paragraph(line, normal_style))
        
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # RECOMMENDATIONS SECTION
    # ========================
    if 'Recommendations' in sections:
        story.append(Paragraph("Recommendations:", section_heading_style))
        
        recommendations_text = sections['Recommendations']
        
        # Format recommendations
        rec_lines = recommendations_text.split('\n')
        for line in rec_lines:
            line = line.strip()
            if line:
                story.append(Paragraph(line, normal_style))
        
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # RISK PROFILE SECTION
    # ========================
    if 'Risk Profile' in sections:
        story.append(Paragraph("Risk Profile:", section_heading_style))
        
        risk_text = sections['Risk Profile']
        story.append(Paragraph(risk_text, normal_style))
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # ESSENTIAL PRECAUTIONS SECTION
    # ========================
    if 'Precautions' in sections:
        story.append(Paragraph("Essential Precautions:", section_heading_style))
        
        precautions_text = sections['Precautions']
        story.append(Paragraph(precautions_text, normal_style))
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # TREATMENT OPTIONS SECTION
    # ========================
    if 'Treatment Options' in sections:
        story.append(Paragraph("Treatment Options:", section_heading_style))
        
        treatment_text = sections['Treatment Options']
        story.append(Paragraph(treatment_text, normal_style))
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # FOLLOW-UP AND MONITORING SECTION
    # ========================
    if 'Follow-Up' in sections:
        story.append(Paragraph("Follow-Up and Monitoring:", section_heading_style))
        
        followup_text = sections['Follow-Up']
        story.append(Paragraph(followup_text, normal_style))
        story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # CONFIDENCE SCORE
    # ========================
    confidence_text = f"<b>AI Classification Confidence:</b> {confidence:.1%}"
    story.append(Paragraph(confidence_text, normal_style))
    story.append(Spacer(1, 0.15*inch))
    
    # ========================
    # DISCLAIMER
    # ========================
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Spacer(1, 0.1*inch))
    
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=normal_style,
        fontSize=8,
        textColor=colors.grey,
        alignment=TA_JUSTIFY,
        italic=True
    )
    
    disclaimer_text = """<b>DISCLAIMER:</b> This report is generated using artificial intelligence analysis 
    and should be considered preliminary. Definitive diagnosis requires in-person evaluation by a 
    board-certified radiologist or orthopedic specialist. Please consult a healthcare professional 
    for confirmation and treatment planning."""
    
    story.append(Paragraph(disclaimer_text, disclaimer_style))
    story.append(Spacer(1, 0.1*inch))
    
    # ========================
    # FOOTER
    # ========================
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        alignment=TA_CENTER,
        textColor=colors.grey
    )
    
    footer_text = f"Generated by AI-Powered Knee Osteoarthritis Analysis System | {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    story.append(Paragraph(footer_text, footer_style))
    
    # Build PDF
    doc.build(story)
    
    return output_path


def create_professional_prescriptive_pdf(report_text, patient_info, kl_grade, 
                                        output_path=None):
    """
    Create a professional prescriptive care plan PDF
    
    Format structure:
    - Header: PRESCRIPTIVE CARE PLAN
    - Subtitle: Knee Osteoarthritis Management
    - Patient Information table
    - Structured sections with clear headings
    - Professional formatting throughout
    """
    
    os.makedirs(OUTPUT_FOLDER, exist_ok=True)
    
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = os.path.join(OUTPUT_FOLDER, f"prescriptive_care_{timestamp}.pdf")
    
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=0.75*inch,
        rightMargin=0.75*inch,
        topMargin=1*inch,
        bottomMargin=0.75*inch
    )
    
    story = []
    styles = getSampleStyleSheet()
    
    # Title style
    title_style = ParagraphStyle(
        'CareTitle',
        parent=styles['Title'],
        fontSize=18,
        textColor=colors.HexColor('#2d8659'),  # Medical green
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
        leading=22
    )
    
    # Subtitle style
    subtitle_style = ParagraphStyle(
        'CareSubtitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2d8659'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica',
        leading=16
    )
    
    # Section heading style
    section_heading_style = ParagraphStyle(
        'CareSectionHeading',
        parent=styles['Heading2'],
        fontSize=11,
        textColor=colors.HexColor('#2d8659'),
        spaceAfter=8,
        spaceBefore=12,
        fontName='Helvetica-Bold',
        leading=13,
        leftIndent=0
    )
    
    # Normal text style
    normal_style = ParagraphStyle(
        'CareNormal',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_LEFT,
        spaceAfter=6,
        leading=13,
        fontName='Helvetica'
    )
    
    # ========================
    # HEADER
    # ========================
    story.append(Paragraph("PRESCRIPTIVE CARE PLAN", title_style))
    story.append(Paragraph("Knee Osteoarthritis Management", subtitle_style))
    
    from reportlab.platypus import HRFlowable
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#2d8659')))
    story.append(Spacer(1, 0.15*inch))
    
    # ========================
    # PATIENT INFORMATION TABLE
    # ========================
    # KL Grade diagnosis
    kl_diagnoses = {
        0: "No Osteoarthritis",
        1: "Doubtful Osteoarthritis",
        2: "Mild Osteoarthritis",
        3: "Moderate Osteoarthritis",
        4: "Severe Osteoarthritis"
    }
    
    patient_data = [
        ['Patient ID:', patient_info.get('Name', 'N/A')],
        ['Age:', patient_info.get('Age', 'N/A')],
        ['Sex:', patient_info.get('Sex', 'N/A')],
        ['Height:', patient_info.get('Height', 'N/A')],
        ['Weight:', patient_info.get('Weight', 'N/A')],
        ['Activity Level:', patient_info.get('Activity Level', 'N/A')],
        ['Diagnosis:', f"KL Grade {kl_grade} - {kl_diagnoses.get(kl_grade, 'OA')}"]
    ]
    
    patient_table = Table(patient_data, colWidths=[2*inch, 4.5*inch])
    patient_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f5e9')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    
    story.append(patient_table)
    story.append(Spacer(1, 0.2*inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Spacer(1, 0.15*inch))
    
    # ========================
    # PARSE AND FORMAT REPORT SECTIONS
    # ========================
    # Parse report text into sections
    lines = report_text.split('\n')
    
    for line in lines:
        line_stripped = line.strip()
        
        if not line_stripped:
            continue
        
        # Check if section header (all caps, or ends with colon)
        if (line_stripped.isupper() and len(line_stripped) < 60) or \
           (line_stripped.endswith(':') and len(line_stripped) < 60 and not line_stripped.startswith('-') and not line_stripped.startswith('•')):
            # Section heading
            story.append(Spacer(1, 0.05*inch))
            story.append(Paragraph(line_stripped, section_heading_style))
        else:
            # Regular content
            # Check if bullet point
            if line_stripped.startswith('•') or line_stripped.startswith('-'):
                story.append(Paragraph(line_stripped, normal_style))
            else:
                story.append(Paragraph(line_stripped, normal_style))
    
    # ========================
    # FOOTER
    # ========================
    story.append(Spacer(1, 0.2*inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Spacer(1, 0.1*inch))
    
    footer_style = ParagraphStyle(
        'CareFooter',
        parent=styles['Normal'],
        fontSize=8,
        alignment=TA_CENTER,
        textColor=colors.grey
    )
    
    footer_text = f"Generated by AI-Powered Prescriptive Care System | {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    story.append(Paragraph(footer_text, footer_style))
    
    # Build PDF
    doc.build(story)
    
    return output_path


# Legacy function names for backwards compatibility
def create_pdf_report(report_text, patient_info, kl_grade, confidence, gradcam_path=None,
                     output_path=None, language='en', prediction_id=None):
    """Legacy wrapper - calls new professional PDF generator"""
    return create_professional_radiology_pdf(
        report_text, patient_info, kl_grade, confidence,
        gradcam_path, output_path, language, prediction_id
    )


def create_prescriptive_pdf(report_text, patient_info, output_path=None):
    """Legacy wrapper - calls new professional PDF generator"""
    kl_grade = patient_info.get('KL_Grade', 0)
    return create_professional_prescriptive_pdf(
        report_text, patient_info, kl_grade, output_path
    )


if __name__ == '__main__':
    # Test PDF generation
    print("Testing Professional PDF Generation")
    
    sample_report = """Clinical History:
65-year-old Male patient with knee pain for 6 months.

Technique:
Standard anteroposterior (AP) and lateral radiographic views of the knee were obtained.
Classification Confidence: 87.5%

Findings:
Definite joint space narrowing is present, more pronounced in the medial compartment.
Small osteophytes are identified at the joint margins.
Mild subchondral sclerosis is noted in the weight-bearing areas.

Conclusion:
1. Mild knee osteoarthritis (Kellgren-Lawrence Grade 2).
2. Recommend conservative management including physical therapy and NSAIDs."""
    
    patient_info = {
        'Name': 'Test Patient',
        'Age': '65',
        'Sex': 'Male',
        'Height': '175 cm',
        'Weight': '80 kg'
    }
    
    pdf_path = create_professional_radiology_pdf(
        sample_report, patient_info, 2, 0.875,
        gradcam_path=None, prediction_id=1
    )
    
    print(f"Test PDF created: {pdf_path}")

